### ISSUE TITLE
Many pages

### ISSUE THREAD

**Issue by 0un** [rewdy/Pico-Pagination#16]
How not to display all pages when there are many?
Now: 1 2 3 4 5 6 7 8 9
Necessary: 1 2 3 ... 8 9

**Comment by rewdy** [comment]
Hi. Unfortunately, the plugin doesn't handle this in it's current state. I think it would be helpful, but I don't think I have the time to figure it out right now. You could maybe come up with a CSS solution? Otherwise, feel free to update the code and submit a pull request.
