### ISSUE TITLE
additional slash on pagination_links

### ISSUE THREAD

**Issue by RandomRouter** [rewdy/Pico-Pagination#19]
When using {{ pagination_links }} the generated URL contains an additional slash which seems to be not necessary. 

I have a subfolder for my blog posts and use pagination_sub_page = true. This leads to the following pagination link containing an additional slash:

http://localhost/pico/**/**blog/1

Blog posts a reachable under the following URL:

http://localhost/pico/blog/my_blog_post

**Comment by RandomRouter** [comment]
duplicate of https://github.com/rewdy/Pico-Pagination/issues/20

**Comment by rewdy** [comment]
You're right, this is an issue. Fix coming shortly. Sorry I'm so late 😞 .

**Comment by rewdy** [comment]
Should be fixed with 1.5! 😁
