### ISSUE TITLE
Pagination is not working properly

### ISSUE THREAD

**Issue by razvanenescu** [rewdy/Pico-Pagination#4]
Hi Andrew,

First I wanted to thank you for this plugin; I followed your instructions to set up the plugin and Pico to use it.

I have one issue though; by the time  I reach the post limit for one page and the plugin kicks in, if I press next page I will the same page - e.g. all the posts listing again as for the first page instead of the one post, following the order and the age criteria.

Any ideas?

Thank you,

Razvan

**Comment by rewdy** [comment]
Oops. I for some reason lost this comment. If you're still having trouble go ahead and open a new issue. Sorry I didn't respond earlier.
