### ISSUE TITLE
Question: Can I grab posts from specific page?

### ISSUE THREAD

**Issue by katavie** [rewdy/Pico-Pagination#7]
Is there a way I can use this plugin to grab posts from, as an example, only page 1 and display them?

**Comment by rewdy** [comment]
Hello @katavie, I am not quite sure what you mean. Are you thinking to show a list of posts on a page other than the site home page? If that is what you want, take a look at the `pagination_sub_page` option in the readme file.

**Comment by katavie** [comment]
I wanted to do something like: display all the posts from the first page and only those. I wouldn't want any of the posts on subsequent pages, because that would be too many. Sorry if my explanation is confusing.

**Comment by rewdy** [comment]
Oh, yeah. That would be easy. Just set up everything as per the main example in the readme file, but just don't display the pagination links. So, where you see `{{pagination_links}}`, just remove that line.

Technically, if someone manipulated the URL manually, they could still find your subsequent pages, but without the links they probably will not.

Give that a try and let me know if it works.

**Comment by katavie** [comment]
Thanks! I'm actually no longer working on the project where I needed to do that, but if I use this plugin again, I'll keep that in mind.
